[TableSchema]
TestTable = [{AttributeName = "PartitionKey", AttributeType = "S"}, {AttributeName = "SortKey", AttributeType = "S"}]

[ItemInput]
    [ItemInput.RequestItems]
        TestTable = [
            {DeleteRequest = {Key = {PartitionKey = {S = "Name"}, SortKey={S = "Idade"}}}}
        ]

