# THIS FILE IS AN EXAMPLE

# Define here the infomations about your table

TableSchema = [
    {AttributeName = "PartitionKey", AttributeType = "S"},
    {AttributeName = "SortKey", AttributeType = "S"}
]

[ItemInput] 
    TableName = "TestTable"
    Key = { PartitionKey = {S = "PartitionKey"}, SortKey = {S = "SortKey"} }