# Configuration file for PutItem Request

TableSchema = [
    {AttributeName = "PartitionKey", AttributeType = "S"}
]

[ItemInput] 
    TableName = "TestTable"
    Item = { PartitionKey = {S = "PartitionKey"}, SortKey = {S = "SortKey"} }