[TableSchema]
TestTable = [{AttributeName = "PartitionKey", AttributeType = "S"}, {AttributeName = "SortKey", AttributeType = "S"}]

[ItemInput]
    TransactItems = [
        {Get = {TableName = "TestTable",Key = {PartitionKey = {S = "PartitionKey"}, SortKey = {S = "SortKey"}}}},
    ]